import type { MigrationMeta } from 'drizzle-orm/migrator';

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface MigrationJournal {
  entries: MigrationEntry[];
}

interface MigrationEntry {
  breakpoints: boolean;
  tag: string;
  when: number;
}

export function generateMigrationAssets(): void {
  const appRoot = join(import.meta.dir, '..');
  const drizzleDir = join(appRoot, 'drizzle');
  const generatedModule = join(appRoot, 'src', 'store', 'db', 'migrations.generated.ts');
  const journalPath = join(drizzleDir, 'meta', '_journal.json');
  const journal = JSON.parse(readFileSync(journalPath, 'utf8')) as MigrationJournal;
  const entries = journal.entries;

  if (entries.length === 0) throw new Error('Drizzle migration journal has no entries');

  for (const entry of entries) {
    if (!existsSync(join(drizzleDir, `${entry.tag}.sql`))) {
      throw new Error(`Drizzle journal entry has no SQL file: ${entry.tag}`);
    }
  }

  const migrations = entries.map((entry): MigrationMeta => {
    const query = readFileSync(join(drizzleDir, `${entry.tag}.sql`), 'utf8');
    return {
      sql: query.split('--> statement-breakpoint'),
      bps: entry.breakpoints,
      folderMillis: entry.when,
      hash: createHash('sha256').update(query).digest('hex')
    };
  });
  const content = renderGeneratedModule(migrations, entries.at(-1)?.when);
  if (!existsSync(generatedModule) || readFileSync(generatedModule, 'utf8') !== content) {
    writeFileSync(generatedModule, content);
  }
}

if (import.meta.main) generateMigrationAssets();

function renderGeneratedModule(migrations: MigrationMeta[], latestMigrationTimestamp: number | undefined): string {
  if (latestMigrationTimestamp === undefined) throw new Error('Drizzle migration journal has no entries');
  return [
    '// Generated by apps/monad/scripts/generate-migration-assets.ts. Do not edit by hand.',
    '',
    "import type { MigrationMeta } from 'drizzle-orm/migrator';",
    '',
    '// biome-ignore format: generated migration data mirrors the source SQL exactly.',
    `export const MIGRATIONS: MigrationMeta[] = ${JSON.stringify(migrations, null, 2)};`,
    '',
    `export const LATEST_MIGRATION_TIMESTAMP = ${latestMigrationTimestamp};`,
    ''
  ].join('\n');
}
