import type { MigrationMeta } from 'drizzle-orm/migrator';

import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, extname, join } from 'node:path';

interface MigrationJournal {
  entries: MigrationEntry[];
}

interface MigrationEntry {
  breakpoints: boolean;
  tag: string;
  when: number;
}

export function renderMigrationAssets(drizzleDir: string): string {
  const journalPath = join(drizzleDir, 'meta', '_journal.json');
  const journal = JSON.parse(readFileSync(journalPath, 'utf8')) as MigrationJournal;
  const entries = journal.entries;

  if (entries.length === 0) throw new Error('Drizzle migration journal has no entries');
  validateMigrationHistory(drizzleDir, entries);

  const migrations = entries.map((entry): MigrationMeta => {
    const query = readFileSync(join(drizzleDir, `${entry.tag}.sql`), 'utf8');
    return {
      sql: query.split('--> statement-breakpoint'),
      bps: entry.breakpoints,
      folderMillis: entry.when,
      hash: createHash('sha256').update(query).digest('hex')
    };
  });
  return renderGeneratedModule(migrations, entries.at(-1)?.when);
}

function validateMigrationHistory(drizzleDir: string, entries: MigrationEntry[]): void {
  const journalTagCounts = new Map<string, number>();
  for (const entry of entries) {
    const count = (journalTagCounts.get(entry.tag) ?? 0) + 1;
    journalTagCounts.set(entry.tag, count);
    if (count > 1) throw new Error(`Drizzle journal contains duplicate migration tag: ${entry.tag}`);
  }

  const sqlTags = readdirSync(drizzleDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && extname(entry.name) === '.sql')
    .map((entry) => basename(entry.name, '.sql'));
  const sqlTagSet = new Set(sqlTags);

  for (const entry of entries) {
    if (!sqlTagSet.has(entry.tag)) throw new Error(`Drizzle journal entry has no SQL file: ${entry.tag}`);
  }
  for (const tag of sqlTags) {
    if (!journalTagCounts.has(tag)) throw new Error(`Drizzle migration SQL file has no journal entry: ${tag}`);
  }
}

export function generateMigrationAssets(): void {
  const appRoot = join(import.meta.dir, '..');
  const drizzleDir = join(appRoot, 'drizzle');
  const generatedModule = join(appRoot, 'src', 'store', 'db', 'migrations.generated.ts');
  const content = renderMigrationAssets(drizzleDir);
  if (!existsSync(generatedModule) || readFileSync(generatedModule, 'utf8') !== content) {
    writeFileSync(generatedModule, content);
  }
}

if (import.meta.main) generateMigrationAssets();

function renderGeneratedModule(migrations: MigrationMeta[], latestMigrationTimestamp: number | undefined): string {
  if (latestMigrationTimestamp === undefined) throw new Error('Drizzle migration journal has no entries');
  return [
    '// Generated by apps/monad/scripts/generate-migration-assets.ts. Do not edit by hand.',
    '',
    "import type { MigrationMeta } from 'drizzle-orm/migrator';",
    '',
    '// biome-ignore format: generated migration data mirrors the source SQL exactly.',
    `export const MIGRATIONS: MigrationMeta[] = ${JSON.stringify(migrations, null, 2)};`,
    '',
    `export const LATEST_MIGRATION_TIMESTAMP = ${latestMigrationTimestamp};`,
    ''
  ].join('\n');
}
