import {
  agentAdapter,
  agentSelectors,
  useCreateAgentMutation,
  useDeleteAgentMutation,
  useGetA2aStatusQuery,
  useGetAgentPromptQuery,
  useGetAgentQuery,
  useGetDefaultAgentQuery,
  useListAgentsQuery,
  useSetAgentPromptMutation,
  useSetDefaultAgentMutation,
  useUpdateAgentMutation
} from './endpoints/agents/index.ts';
import {
  approvalRuleSelectors,
  approvalsApi,
  useClearApprovalsMutation,
  useListApprovalsQuery,
  useRevokeApprovalMutation
} from './endpoints/approvals/index.ts';
import {
  atomPackAdapter,
  atomPackSelectors,
  atomsApi,
  useBrowseSkillsQuery,
  useCheckSkillUpdatesQuery,
  useDiscoverAtomKindsMutation,
  useFetchSkillDetailQuery,
  useGetSkillContentQuery,
  useInstallAtomPackMutation,
  useInstallMcpAtomMutation,
  useInstallMcpBinaryMutation,
  useInstallSkillMutation,
  useLazyBrowseSkillsQuery,
  useLazyCheckSkillUpdatesQuery,
  useLazyFetchSkillDetailQuery,
  useLazyGetSkillContentQuery,
  useLazySearchSkillsQuery,
  useListAtomKindsQuery,
  useListAtomPacksQuery,
  useListInstalledMcpQuery,
  useListInstalledSkillsQuery,
  useListWorkspaceExperiencesQuery,
  useRemoveAtomPackMutation,
  useRemoveMcpAtomMutation,
  useRemoveSkillMutation,
  useSearchSkillsQuery,
  useSetAtomPackEnabledMutation,
  useSetAtomPinMutation,
  useSetMcpAtomEnabledMutation,
  useUpdateSkillContentMutation,
  useUpdateSkillMutation,
  useUploadAtomPackMutation,
  useUploadSkillMutation
} from './endpoints/atoms/index.ts';
import {
  useDownloadAttachmentMutation,
  useGetAttachmentQuery,
  useLazyGetAttachmentQuery
} from './endpoints/attachments/index.ts';
import { useSendChannelMessageMutation } from './endpoints/channels/index.ts';
import { commandsApi, useLazyListCommandsQuery, useListCommandsQuery } from './endpoints/commands/index.ts';
import { useOpenDraftAttachmentMutation } from './endpoints/draft-attachments/index.ts';
import {
  externalAgentSessionAdapter,
  externalAgentSessionSelectors,
  useApproveExternalAgentSessionMutation,
  useGetExternalAgentAuthQuery,
  useGetExternalAgentObservationQuery,
  useGetExternalAgentSessionQuery,
  useGetExternalAgentUsageQuery,
  useGetNativeAgentDeliveryObservationQuery,
  useGetNativeAgentDeliveryQuery,
  useHeartbeatExternalAgentAuthMutation,
  useInputExternalAgentAuthMutation,
  useInputExternalAgentSessionMutation,
  useLazyGetExternalAgentAuthStatusQuery,
  useLazyGetExternalAgentHistoryPageQuery,
  useLazyGetExternalAgentObservationQuery,
  useLazyGetExternalAgentUsageQuery,
  useLazyGetNativeAgentDeliveryObservationQuery,
  useListExternalAgentSessionSummariesQuery,
  useListExternalAgentSessionsQuery,
  useListLiveExternalAgentSessionsQuery,
  useResizeExternalAgentAuthMutation,
  useResizeExternalAgentSessionMutation,
  useStartExternalAgentAuthMutation,
  useStartExternalAgentMutation,
  useStopExternalAgentAuthMutation,
  useStopExternalAgentSessionMutation,
  useStreamExternalAgentUiObservationQuery
} from './endpoints/external-agent/index.ts';
import { graphApi, useGetGraphQuery } from './endpoints/graph/index.ts';
import { inboxApi, useListMentionInboxQuery } from './endpoints/inbox/index.ts';
import { indexerApi, useGetIndexerStatusQuery } from './endpoints/indexer/get-indexer-status.ts';
import { useInitStatusQuery, useSetInitHomeMutation } from './endpoints/init/index.ts';
import { lawsApi, useGetLawsQuery } from './endpoints/laws/index.ts';
import { licensesApi, useListLicensesQuery } from './endpoints/licenses/index.ts';
import { mem0DataApi, useGetMem0DataQuery } from './endpoints/mem0-data/index.ts';
import {
  factSelectors,
  memoryApi,
  useAddMemoryFactMutation,
  useEditMemoryFactMutation,
  useForgetMemoryFactMutation,
  useGetMemoryCoreQuery,
  useGetMemoryStatusQuery,
  useListMemoryFactsQuery,
  usePutMemoryCoreMutation,
  useSetMem0ModelsMutation,
  useSetMemoryBackendMutation,
  useSetMemoryGraphMutation
} from './endpoints/memory/index.ts';
import {
  projectSessionAdapter,
  projectSessionSelectors,
  useCreateProjectSessionMutation,
  useCreateWorkplaceProjectMutation,
  useDeleteWorkplaceProjectMutation,
  useGetWorkplaceProjectQuery,
  useListProjectSessionsQuery,
  useListWorkplaceProjectsQuery,
  useSendProjectMessageMutation,
  useUpdateWorkplaceProjectMutation,
  workplaceProjectAdapter,
  workplaceProjectSelectors
} from './endpoints/projects/index.ts';
import {
  sessionAdapter,
  sessionMemberAdapter,
  sessionMemberSelectors,
  sessionSelectors,
  useAbortSessionMutation,
  useBranchSessionMutation,
  useCreateSessionMutation,
  useDeleteSessionMutation,
  useForwardToAcpMutation,
  useGenerateMutation,
  useInviteSessionMemberMutation,
  useLazyGetUiItemsWindowQuery,
  useListSessionMembersQuery,
  useListSessionsQuery,
  useRemoveSessionMemberMutation,
  useResetSessionMutation,
  useRestoreSessionMutation,
  useSearchSessionsQuery,
  useSendMessageMutation,
  useSpawnSessionMemberMutation,
  useStreamControlQuery,
  useStreamSessionQuery,
  useStreamUiItemsQuery,
  useUndoDeleteSessionMutation,
  useUpdateSessionMutation,
  useWorkspaceActionMutation,
  useWorkspaceGitQuery,
  useWorkspaceMetaQuery
} from './endpoints/sessions/index.ts';
import {
  acpAgentAdapter,
  acpAgentSelectors,
  useDeleteAcpAgentMutation,
  useListAcpAgentPresetsQuery,
  useListAcpAgentsQuery,
  useUpsertAcpAgentMutation
} from './endpoints/settings/acp-agents/index.ts';
import { useGetAppearanceQuery, useSetAppearanceMutation } from './endpoints/settings/appearance/index.ts';
import { useGetBrowserPresetQuery, useSetBrowserPresetMutation } from './endpoints/settings/browser-preset/index.ts';
import {
  useGetCapabilityInventoryQuery,
  useOpenCapabilityInventoryLocationMutation
} from './endpoints/settings/capability-inventory/index.ts';
import {
  channelAdapter,
  channelPairingSelectors,
  channelSelectors,
  channelsApi,
  useApproveChannelPairingMutation,
  useChannelStatusQuery,
  useDeleteChannelMutation,
  useListChannelPairingsQuery,
  useListChannelsQuery,
  useSetChannelCredentialMutation,
  useUpsertChannelMutation
} from './endpoints/settings/channels/index.ts';
import { useGetComputerPresetQuery, useSetComputerPresetMutation } from './endpoints/settings/computer-preset/index.ts';
import { useGetDeveloperQuery, useSetDeveloperMutation } from './endpoints/settings/developer/index.ts';
import {
  externalAgentAdapter,
  externalAgentSelectors,
  useDeleteExternalAgentMutation,
  useListExternalAgentPresetsQuery,
  useListExternalAgentsQuery,
  useUpsertExternalAgentMutation
} from './endpoints/settings/external-agents/index.ts';
import { useGetHooksQuery, useSetHooksMutation } from './endpoints/settings/hooks/index.ts';
import {
  useApplySettingsImportMutation,
  usePreviewSettingsImportMutation
} from './endpoints/settings/import-settings/index.ts';
import {
  localeAdapter,
  localeApi,
  localeSelectors,
  useGetCatalogQuery,
  useGetLocaleQuery,
  useListLocalesQuery,
  useSetLocaleMutation
} from './endpoints/settings/locale/index.ts';
import {
  mcpServerAdapter,
  mcpServerSelectors,
  useAuthorizeMcpServerMutation,
  useDeleteMcpServerMutation,
  useLazyListMcpServerStatusQuery,
  useLazySearchMcpRegistryQuery,
  useListMcpCatalogQuery,
  useListMcpServerStatusQuery,
  useListMcpServersQuery,
  useReconnectMcpServerMutation,
  useSearchMcpRegistryQuery,
  useUpsertMcpServerMutation
} from './endpoints/settings/mcp-servers/index.ts';
import {
  credentialAdapter,
  credentialSelectors,
  modelAdapter,
  modelApi,
  modelSelectors,
  profileAdapter,
  profileSelectors,
  providerAdapter,
  providerSelectors,
  useAddCredentialMutation,
  useDeleteCredentialMutation,
  useDeleteProfileMutation,
  useDeleteProviderMutation,
  useGetDefaultQuery,
  useGetRolesQuery,
  useLazyListModelsQuery,
  useListCredentialsQuery,
  useListModelsQuery,
  useListProfilesQuery,
  useListProvidersQuery,
  useProviderCatalogQuery,
  useReindexEmbeddingsMutation,
  useRenameProfileMutation,
  useSetDefaultMutation,
  useSetProfileMutation,
  useSetProviderMutation,
  useSetRolesMutation,
  useTestConnectionMutation,
  useTestCredentialMutation,
  useTranscribeAudioMutation
} from './endpoints/settings/model/index.ts';
import {
  useGetNetworkQuery,
  useProbeNetworkMutation,
  useSetNetworkMutation
} from './endpoints/settings/network/index.ts';
import { useGetObscuraQuery, useSetObscuraMutation } from './endpoints/settings/obscura/index.ts';
import { useGetOpenaiCompatQuery, useSetOpenaiCompatMutation } from './endpoints/settings/openai-compat/index.ts';
import {
  peerAdapter,
  peerSelectors,
  useDeletePeerMutation,
  useGetPeerQuery,
  useListPeersQuery,
  useSetPeerCredentialMutation,
  useSetPeerEnabledMutation,
  useTestPeerConnectionMutation,
  useUpsertPeerMutation
} from './endpoints/settings/peers/index.ts';
import { useGetProfileSettingsQuery, useSetProfileSettingsMutation } from './endpoints/settings/profile/index.ts';
import {
  useActivateSandboxMutation,
  useGetSandboxQuery,
  useSetSandboxMutation
} from './endpoints/settings/sandbox/index.ts';
import { useGetSkillsSettingsQuery, useSetSkillsSettingsMutation } from './endpoints/settings/skills/index.ts';
import {
  useGetStartupQuery,
  useOpenStartupSettingsMutation,
  useSetStartupMutation
} from './endpoints/settings/startup/index.ts';
import {
  useGetToolBackendsQuery,
  useInitDockerBackendMutation,
  useSetToolBackendsMutation
} from './endpoints/settings/tool-backends/index.ts';
import { skillsApi, useListSkillsQuery } from './endpoints/skills/index.ts';
import { useGetHealthQuery } from './endpoints/system/get-health.ts';
import { useGetSystemUpgradeQuery } from './endpoints/system/get-system-upgrade.ts';
import { usePickDirectoryMutation } from './endpoints/system/pick-directory.ts';
import { useStartSystemUpgradeMutation } from './endpoints/system/start-system-upgrade.ts';
import { useApproveToolMutation } from './endpoints/tools/approve-tool.ts';
import { useClarifyRespondMutation } from './endpoints/tools/clarify-respond.ts';
import { useGetStatsQuery } from './endpoints/usage/get-stats.ts';
import { useGetUsageQuery } from './endpoints/usage/get-usage.ts';
import { useResetUsageMutation } from './endpoints/usage/reset-usage.ts';

export const monadApi = modelApi;

export type { ContextNotice, MemorySuggestion } from './endpoints/sessions/index.ts';

export {
  acpAgentAdapter,
  acpAgentSelectors,
  agentAdapter,
  agentSelectors,
  approvalRuleSelectors,
  approvalsApi,
  atomPackAdapter,
  atomPackSelectors,
  atomsApi,
  channelAdapter,
  channelPairingSelectors,
  channelSelectors,
  channelsApi,
  commandsApi,
  credentialAdapter,
  credentialSelectors,
  externalAgentAdapter,
  externalAgentSelectors,
  externalAgentSessionAdapter,
  externalAgentSessionSelectors,
  factSelectors,
  graphApi,
  inboxApi,
  indexerApi,
  lawsApi,
  licensesApi,
  localeAdapter,
  localeApi,
  localeSelectors,
  mcpServerAdapter,
  mcpServerSelectors,
  mem0DataApi,
  memoryApi,
  modelAdapter,
  modelSelectors,
  peerAdapter,
  peerSelectors,
  profileAdapter,
  profileSelectors,
  projectSessionAdapter,
  projectSessionSelectors,
  providerAdapter,
  providerSelectors,
  sessionAdapter,
  sessionMemberAdapter,
  sessionMemberSelectors,
  sessionSelectors,
  skillsApi,
  useAbortSessionMutation,
  useActivateSandboxMutation,
  useAddCredentialMutation,
  useAddMemoryFactMutation,
  useApplySettingsImportMutation,
  useApproveChannelPairingMutation,
  useApproveExternalAgentSessionMutation,
  useApproveToolMutation,
  useAuthorizeMcpServerMutation,
  useBranchSessionMutation,
  useBrowseSkillsQuery,
  useChannelStatusQuery,
  useCheckSkillUpdatesQuery,
  useClarifyRespondMutation,
  useClearApprovalsMutation,
  useCreateAgentMutation,
  useCreateProjectSessionMutation,
  useCreateSessionMutation,
  useCreateWorkplaceProjectMutation,
  useDeleteAcpAgentMutation,
  useDeleteAgentMutation,
  useDeleteChannelMutation,
  useDeleteCredentialMutation,
  useDeleteExternalAgentMutation,
  useDeleteMcpServerMutation,
  useDeletePeerMutation,
  useDeleteProfileMutation,
  useDeleteProviderMutation,
  useDeleteSessionMutation,
  useDeleteWorkplaceProjectMutation,
  useDiscoverAtomKindsMutation,
  useDownloadAttachmentMutation,
  useEditMemoryFactMutation,
  useFetchSkillDetailQuery,
  useForgetMemoryFactMutation,
  useForwardToAcpMutation,
  useGenerateMutation,
  useGetA2aStatusQuery,
  useGetAgentPromptQuery,
  useGetAgentQuery,
  useGetAppearanceQuery,
  useGetAttachmentQuery,
  useGetBrowserPresetQuery,
  useGetCapabilityInventoryQuery,
  useGetCatalogQuery,
  useGetComputerPresetQuery,
  useGetDefaultAgentQuery,
  useGetDefaultQuery,
  useGetDeveloperQuery,
  useGetExternalAgentAuthQuery,
  useGetExternalAgentObservationQuery,
  useGetExternalAgentSessionQuery,
  useGetExternalAgentUsageQuery,
  useGetGraphQuery,
  useGetHealthQuery,
  useGetHooksQuery,
  useGetIndexerStatusQuery,
  useGetLawsQuery,
  useGetLocaleQuery,
  useGetMem0DataQuery,
  useGetMemoryCoreQuery,
  useGetMemoryStatusQuery,
  useGetNativeAgentDeliveryObservationQuery,
  useGetNativeAgentDeliveryQuery,
  useGetNetworkQuery,
  useGetObscuraQuery,
  useGetOpenaiCompatQuery,
  useGetPeerQuery,
  useGetProfileSettingsQuery,
  useGetRolesQuery,
  useGetSandboxQuery,
  useGetSkillContentQuery,
  useGetSkillsSettingsQuery,
  useGetStartupQuery,
  useGetStatsQuery,
  useGetSystemUpgradeQuery,
  useGetToolBackendsQuery,
  useGetUsageQuery,
  useGetWorkplaceProjectQuery,
  useHeartbeatExternalAgentAuthMutation,
  useInitDockerBackendMutation,
  useInitStatusQuery,
  useInputExternalAgentAuthMutation,
  useInputExternalAgentSessionMutation,
  useInstallAtomPackMutation,
  useInstallMcpAtomMutation,
  useInstallMcpBinaryMutation,
  useInstallSkillMutation,
  useInviteSessionMemberMutation,
  useLazyBrowseSkillsQuery,
  useLazyCheckSkillUpdatesQuery,
  useLazyFetchSkillDetailQuery,
  useLazyGetAttachmentQuery,
  useLazyGetExternalAgentAuthStatusQuery,
  useLazyGetExternalAgentHistoryPageQuery,
  useLazyGetExternalAgentObservationQuery,
  useLazyGetExternalAgentUsageQuery,
  useLazyGetNativeAgentDeliveryObservationQuery,
  useLazyGetSkillContentQuery,
  useLazyGetUiItemsWindowQuery,
  useLazyListCommandsQuery,
  useLazyListMcpServerStatusQuery,
  useLazyListModelsQuery,
  useLazySearchMcpRegistryQuery,
  useLazySearchSkillsQuery,
  useListAcpAgentPresetsQuery,
  useListAcpAgentsQuery,
  useListAgentsQuery,
  useListApprovalsQuery,
  useListAtomKindsQuery,
  useListAtomPacksQuery,
  useListChannelPairingsQuery,
  useListChannelsQuery,
  useListCommandsQuery,
  useListCredentialsQuery,
  useListExternalAgentPresetsQuery,
  useListExternalAgentSessionSummariesQuery,
  useListExternalAgentSessionsQuery,
  useListExternalAgentsQuery,
  useListInstalledMcpQuery,
  useListInstalledSkillsQuery,
  useListLicensesQuery,
  useListLiveExternalAgentSessionsQuery,
  useListLocalesQuery,
  useListMcpCatalogQuery,
  useListMcpServerStatusQuery,
  useListMcpServersQuery,
  useListMemoryFactsQuery,
  useListMentionInboxQuery,
  useListModelsQuery,
  useListPeersQuery,
  useListProfilesQuery,
  useListProjectSessionsQuery,
  useListProvidersQuery,
  useListSessionMembersQuery,
  useListSessionsQuery,
  useListSkillsQuery,
  useListWorkplaceProjectsQuery,
  useListWorkspaceExperiencesQuery,
  useOpenCapabilityInventoryLocationMutation,
  useOpenDraftAttachmentMutation,
  useOpenStartupSettingsMutation,
  usePickDirectoryMutation,
  usePreviewSettingsImportMutation,
  useProbeNetworkMutation,
  useProviderCatalogQuery,
  usePutMemoryCoreMutation,
  useReconnectMcpServerMutation,
  useReindexEmbeddingsMutation,
  useRemoveAtomPackMutation,
  useRemoveMcpAtomMutation,
  useRemoveSessionMemberMutation,
  useRemoveSkillMutation,
  useRenameProfileMutation,
  useResetSessionMutation,
  useResetUsageMutation,
  useResizeExternalAgentAuthMutation,
  useResizeExternalAgentSessionMutation,
  useRestoreSessionMutation,
  useRevokeApprovalMutation,
  useSearchMcpRegistryQuery,
  useSearchSessionsQuery,
  useSearchSkillsQuery,
  useSendChannelMessageMutation,
  useSendMessageMutation,
  useSendProjectMessageMutation,
  useSetAgentPromptMutation,
  useSetAppearanceMutation,
  useSetAtomPackEnabledMutation,
  useSetAtomPinMutation,
  useSetBrowserPresetMutation,
  useSetChannelCredentialMutation,
  useSetComputerPresetMutation,
  useSetDefaultAgentMutation,
  useSetDefaultMutation,
  useSetDeveloperMutation,
  useSetHooksMutation,
  useSetInitHomeMutation,
  useSetLocaleMutation,
  useSetMcpAtomEnabledMutation,
  useSetMem0ModelsMutation,
  useSetMemoryBackendMutation,
  useSetMemoryGraphMutation,
  useSetNetworkMutation,
  useSetObscuraMutation,
  useSetOpenaiCompatMutation,
  useSetPeerCredentialMutation,
  useSetPeerEnabledMutation,
  useSetProfileMutation,
  useSetProfileSettingsMutation,
  useSetProviderMutation,
  useSetRolesMutation,
  useSetSandboxMutation,
  useSetSkillsSettingsMutation,
  useSetStartupMutation,
  useSetToolBackendsMutation,
  useSpawnSessionMemberMutation,
  useStartExternalAgentAuthMutation,
  useStartExternalAgentMutation,
  useStartSystemUpgradeMutation,
  useStopExternalAgentAuthMutation,
  useStopExternalAgentSessionMutation,
  useStreamControlQuery,
  useStreamExternalAgentUiObservationQuery,
  useStreamSessionQuery,
  useStreamUiItemsQuery,
  useTestConnectionMutation,
  useTestCredentialMutation,
  useTestPeerConnectionMutation,
  useTranscribeAudioMutation,
  useUndoDeleteSessionMutation,
  useUpdateAgentMutation,
  useUpdateSessionMutation,
  useUpdateSkillContentMutation,
  useUpdateSkillMutation,
  useUpdateWorkplaceProjectMutation,
  useUploadAtomPackMutation,
  useUploadSkillMutation,
  useUpsertAcpAgentMutation,
  useUpsertChannelMutation,
  useUpsertExternalAgentMutation,
  useUpsertMcpServerMutation,
  useUpsertPeerMutation,
  useWorkspaceActionMutation,
  useWorkspaceGitQuery,
  useWorkspaceMetaQuery,
  workplaceProjectAdapter,
  workplaceProjectSelectors
};
