import {
  useCreateAgentMutation,
  useDeleteAgentMutation,
  useGetAgentPromptQuery,
  useGetAgentQuery,
  useGetDefaultAgentQuery,
  useListAgentsQuery,
  useSetAgentPromptMutation,
  useSetDefaultAgentMutation,
  useUpdateAgentMutation
} from './endpoints/agents/index.ts';
import {
  approvalsApi,
  useClearApprovalsMutation,
  useListApprovalsQuery,
  useRevokeApprovalMutation
} from './endpoints/approvals/index.ts';
import {
  atomsApi,
  useBrowseSkillsQuery,
  useCheckSkillUpdatesQuery,
  useDiscoverAtomKindsMutation,
  useFetchSkillDetailQuery,
  useGetSkillContentQuery,
  useInstallAtomPackMutation,
  useInstallMcpAtomMutation,
  useInstallMcpBinaryMutation,
  useInstallSkillMutation,
  useLazyBrowseSkillsQuery,
  useLazyCheckSkillUpdatesQuery,
  useLazyFetchSkillDetailQuery,
  useLazyGetSkillContentQuery,
  useLazySearchSkillsQuery,
  useListAtomKindsQuery,
  useListAtomPacksQuery,
  useListInstalledMcpQuery,
  useListInstalledSkillsQuery,
  useRemoveAtomPackMutation,
  useRemoveMcpAtomMutation,
  useRemoveSkillMutation,
  useSearchSkillsQuery,
  useSetAtomPackEnabledMutation,
  useSetAtomPinMutation,
  useSetMcpAtomEnabledMutation,
  useUpdateSkillContentMutation,
  useUpdateSkillMutation,
  useUploadSkillMutation
} from './endpoints/atoms/index.ts';
import { useSendChannelMessageMutation } from './endpoints/channels/index.ts';
import { commandsApi, useListCommandsQuery } from './endpoints/commands/index.ts';
import { graphApi, useGetGraphQuery } from './endpoints/graph/index.ts';
import { indexerApi, useGetIndexerStatusQuery } from './endpoints/indexer/get-indexer-status.ts';
import { useInitStatusQuery, useSetInitHomeMutation } from './endpoints/init/index.ts';
import { licensesApi, useListLicensesQuery } from './endpoints/licenses/index.ts';
import { mem0DataApi, useGetMem0DataQuery } from './endpoints/mem0-data/index.ts';
import {
  memoryApi,
  useAddMemoryFactMutation,
  useEditMemoryFactMutation,
  useForgetMemoryFactMutation,
  useGetMemoryCoreQuery,
  useGetMemoryStatusQuery,
  useListMemoryFactsQuery,
  usePutMemoryCoreMutation,
  useSetMem0ModelsMutation,
  useSetMemoryBackendMutation,
  useSetMemoryGraphMutation
} from './endpoints/memory/index.ts';
import {
  useApproveNativeCliSessionMutation,
  useInputNativeCliSessionMutation,
  useResizeNativeCliSessionMutation,
  useStartNativeCliAgentMutation,
  useStopNativeCliSessionMutation
} from './endpoints/native-cli/index.ts';
import { useSendProjectMessageMutation } from './endpoints/projects/index.ts';
import {
  sessionAdapter,
  sessionSelectors,
  useAbortSessionMutation,
  useBranchSessionMutation,
  useCreateSessionMutation,
  useDeleteSessionMutation,
  useForwardToAcpMutation,
  useGenerateMutation,
  useGetMessagesInfiniteQuery,
  useLazyGetUiItemsWindowQuery,
  useListSessionsQuery,
  useProvenanceQuery,
  useResetSessionMutation,
  useRestoreSessionMutation,
  useSearchSessionsQuery,
  useSendMessageMutation,
  useStreamControlQuery,
  useStreamSessionQuery,
  useStreamUiItemsQuery,
  useUpdateSessionMutation,
  useWorkspaceGitQuery
} from './endpoints/sessions/index.ts';
import {
  acpAgentAdapter,
  acpAgentSelectors,
  useDeleteAcpAgentMutation,
  useListAcpAgentPresetsQuery,
  useListAcpAgentsQuery,
  useUpsertAcpAgentMutation
} from './endpoints/settings/acp-agents/index.ts';
import {
  channelAdapter,
  channelSelectors,
  channelsApi,
  useApproveChannelPairingMutation,
  useChannelStatusQuery,
  useDeleteChannelMutation,
  useListChannelPairingsQuery,
  useListChannelsQuery,
  useSetChannelCredentialMutation,
  useUpsertChannelMutation
} from './endpoints/settings/channels/index.ts';
import { useGetDeveloperQuery, useSetDeveloperMutation } from './endpoints/settings/developer/index.ts';
import { useGetHooksQuery, useSetHooksMutation } from './endpoints/settings/hooks/index.ts';
import { useApplySettingsImportMutation, usePreviewSettingsImportMutation } from './endpoints/settings/import/index.ts';
import {
  localeAdapter,
  localeApi,
  localeSelectors,
  useGetCatalogQuery,
  useGetLocaleQuery,
  useListLocalesQuery,
  useSetLocaleMutation
} from './endpoints/settings/locale/index.ts';
import {
  mcpServerAdapter,
  mcpServerSelectors,
  useAuthorizeMcpServerMutation,
  useDeleteMcpServerMutation,
  useLazySearchMcpRegistryQuery,
  useListMcpCatalogQuery,
  useListMcpServerStatusQuery,
  useListMcpServersQuery,
  useReconnectMcpServerMutation,
  useSearchMcpRegistryQuery,
  useUpsertMcpServerMutation
} from './endpoints/settings/mcp-servers/index.ts';
import {
  credentialAdapter,
  credentialSelectors,
  modelAdapter,
  modelApi,
  modelSelectors,
  profileAdapter,
  profileSelectors,
  providerAdapter,
  providerSelectors,
  useAddCredentialMutation,
  useDeleteCredentialMutation,
  useDeleteProfileMutation,
  useDeleteProviderMutation,
  useGetDefaultQuery,
  useGetRolesQuery,
  useListCredentialsQuery,
  useListModelsQuery,
  useListProfilesQuery,
  useListProvidersQuery,
  useProviderCatalogQuery,
  useReindexEmbeddingsMutation,
  useRenameProfileMutation,
  useSetDefaultMutation,
  useSetProfileMutation,
  useSetProviderMutation,
  useSetRolesMutation,
  useTestConnectionMutation,
  useTestCredentialMutation
} from './endpoints/settings/model/index.ts';
import {
  nativeCliAgentAdapter,
  nativeCliAgentSelectors,
  useDeleteNativeCliAgentMutation,
  useListNativeCliAgentPresetsQuery,
  useListNativeCliAgentsQuery,
  useUpsertNativeCliAgentMutation
} from './endpoints/settings/native-cli-agents/index.ts';
import { useGetNetworkQuery, useSetNetworkMutation } from './endpoints/settings/network/index.ts';
import { useGetObscuraQuery, useSetObscuraMutation } from './endpoints/settings/obscura/index.ts';
import { useGetOpenaiCompatQuery, useSetOpenaiCompatMutation } from './endpoints/settings/openai-compat/index.ts';
import { useGetSandboxQuery, useSetSandboxMutation } from './endpoints/settings/sandbox/index.ts';
import { useGetSkillsSettingsQuery, useSetSkillsSettingsMutation } from './endpoints/settings/skills/index.ts';
import { useGetToolBackendsQuery, useSetToolBackendsMutation } from './endpoints/settings/tool-backends/index.ts';
import { skillsApi, useListSkillsQuery } from './endpoints/skills/index.ts';
import { useGetHealthQuery } from './endpoints/system/get-health.ts';
import { usePickDirectoryMutation } from './endpoints/system/pick-directory.ts';
import { useApproveToolMutation } from './endpoints/tools/approve-tool.ts';
import { useClarifyRespondMutation } from './endpoints/tools/clarify-respond.ts';
import { useGetStatsQuery } from './endpoints/usage/get-stats.ts';
import { useGetUsageQuery } from './endpoints/usage/get-usage.ts';
import { useResetUsageMutation } from './endpoints/usage/reset-usage.ts';

export const monadApi = modelApi;

export {
  acpAgentAdapter,
  acpAgentSelectors,
  approvalsApi,
  atomsApi,
  channelAdapter,
  channelSelectors,
  channelsApi,
  commandsApi,
  credentialAdapter,
  credentialSelectors,
  graphApi,
  indexerApi,
  licensesApi,
  localeAdapter,
  localeApi,
  localeSelectors,
  mcpServerAdapter,
  mcpServerSelectors,
  mem0DataApi,
  memoryApi,
  modelAdapter,
  modelSelectors,
  nativeCliAgentAdapter,
  nativeCliAgentSelectors,
  profileAdapter,
  profileSelectors,
  providerAdapter,
  providerSelectors,
  sessionAdapter,
  sessionSelectors,
  skillsApi,
  useAbortSessionMutation,
  useAddCredentialMutation,
  useAddMemoryFactMutation,
  useApplySettingsImportMutation,
  useApproveChannelPairingMutation,
  useApproveNativeCliSessionMutation,
  useApproveToolMutation,
  useAuthorizeMcpServerMutation,
  useBranchSessionMutation,
  useBrowseSkillsQuery,
  useChannelStatusQuery,
  useCheckSkillUpdatesQuery,
  useClarifyRespondMutation,
  useClearApprovalsMutation,
  useCreateAgentMutation,
  useCreateSessionMutation,
  useDeleteAcpAgentMutation,
  useDeleteAgentMutation,
  useDeleteChannelMutation,
  useDeleteCredentialMutation,
  useDeleteMcpServerMutation,
  useDeleteNativeCliAgentMutation,
  useDeleteProfileMutation,
  useDeleteProviderMutation,
  useDeleteSessionMutation,
  useDiscoverAtomKindsMutation,
  useEditMemoryFactMutation,
  useFetchSkillDetailQuery,
  useForgetMemoryFactMutation,
  useForwardToAcpMutation,
  useGenerateMutation,
  useGetAgentPromptQuery,
  useGetAgentQuery,
  useGetCatalogQuery,
  useGetDefaultAgentQuery,
  useGetDefaultQuery,
  useGetDeveloperQuery,
  useGetGraphQuery,
  useGetHealthQuery,
  useGetHooksQuery,
  useGetIndexerStatusQuery,
  useGetLocaleQuery,
  useGetMem0DataQuery,
  useGetMemoryCoreQuery,
  useGetMemoryStatusQuery,
  useGetMessagesInfiniteQuery,
  useGetNetworkQuery,
  useGetObscuraQuery,
  useGetOpenaiCompatQuery,
  useGetRolesQuery,
  useGetSandboxQuery,
  useGetSkillContentQuery,
  useGetSkillsSettingsQuery,
  useGetStatsQuery,
  useGetToolBackendsQuery,
  useGetUsageQuery,
  useInitStatusQuery,
  useInputNativeCliSessionMutation,
  useInstallAtomPackMutation,
  useInstallMcpAtomMutation,
  useInstallMcpBinaryMutation,
  useInstallSkillMutation,
  useLazyBrowseSkillsQuery,
  useLazyCheckSkillUpdatesQuery,
  useLazyFetchSkillDetailQuery,
  useLazyGetSkillContentQuery,
  useLazyGetUiItemsWindowQuery,
  useLazySearchMcpRegistryQuery,
  useLazySearchSkillsQuery,
  useListAcpAgentPresetsQuery,
  useListAcpAgentsQuery,
  useListAgentsQuery,
  useListApprovalsQuery,
  useListAtomKindsQuery,
  useListAtomPacksQuery,
  useListChannelPairingsQuery,
  useListChannelsQuery,
  useListCommandsQuery,
  useListCredentialsQuery,
  useListInstalledMcpQuery,
  useListInstalledSkillsQuery,
  useListLicensesQuery,
  useListLocalesQuery,
  useListMcpCatalogQuery,
  useListMcpServerStatusQuery,
  useListMcpServersQuery,
  useListMemoryFactsQuery,
  useListModelsQuery,
  useListNativeCliAgentPresetsQuery,
  useListNativeCliAgentsQuery,
  useListProfilesQuery,
  useListProvidersQuery,
  useListSessionsQuery,
  useListSkillsQuery,
  usePickDirectoryMutation,
  usePreviewSettingsImportMutation,
  useProvenanceQuery,
  useProviderCatalogQuery,
  usePutMemoryCoreMutation,
  useReconnectMcpServerMutation,
  useReindexEmbeddingsMutation,
  useRemoveAtomPackMutation,
  useRemoveMcpAtomMutation,
  useRemoveSkillMutation,
  useRenameProfileMutation,
  useResetSessionMutation,
  useResetUsageMutation,
  useResizeNativeCliSessionMutation,
  useRestoreSessionMutation,
  useRevokeApprovalMutation,
  useSearchMcpRegistryQuery,
  useSearchSessionsQuery,
  useSearchSkillsQuery,
  useSendChannelMessageMutation,
  useSendMessageMutation,
  useSendProjectMessageMutation,
  useSetAgentPromptMutation,
  useSetAtomPackEnabledMutation,
  useSetAtomPinMutation,
  useSetChannelCredentialMutation,
  useSetDefaultAgentMutation,
  useSetDefaultMutation,
  useSetDeveloperMutation,
  useSetHooksMutation,
  useSetInitHomeMutation,
  useSetLocaleMutation,
  useSetMcpAtomEnabledMutation,
  useSetMem0ModelsMutation,
  useSetMemoryBackendMutation,
  useSetMemoryGraphMutation,
  useSetNetworkMutation,
  useSetObscuraMutation,
  useSetOpenaiCompatMutation,
  useSetProfileMutation,
  useSetProviderMutation,
  useSetRolesMutation,
  useSetSandboxMutation,
  useSetSkillsSettingsMutation,
  useSetToolBackendsMutation,
  useStartNativeCliAgentMutation,
  useStopNativeCliSessionMutation,
  useStreamControlQuery,
  useStreamSessionQuery,
  useStreamUiItemsQuery,
  useTestConnectionMutation,
  useTestCredentialMutation,
  useUpdateAgentMutation,
  useUpdateSessionMutation,
  useUpdateSkillContentMutation,
  useUpdateSkillMutation,
  useUploadSkillMutation,
  useUpsertAcpAgentMutation,
  useUpsertChannelMutation,
  useUpsertMcpServerMutation,
  useUpsertNativeCliAgentMutation,
  useWorkspaceGitQuery
};
