import {
  agentAdapter,
  agentSelectors,
  useCreateAgentMutation,
  useDeleteAgentMutation,
  useGetA2aStatusQuery,
  useGetAgentPromptQuery,
  useGetAgentQuery,
  useGetDefaultAgentQuery,
  useInstallAgentMcpMutation,
  useListAgentsQuery,
  useSetAgentPromptMutation,
  useSetDefaultAgentMutation,
  useUpdateAgentMutation
} from './endpoints/agents/index.ts';
import {
  approvalRuleSelectors,
  approvalsApi,
  useClearApprovalsMutation,
  useListApprovalsQuery,
  useRevokeApprovalMutation
} from './endpoints/approvals/index.ts';
import {
  atomPackAdapter,
  atomPackSelectors,
  atomsApi,
  useBrowseSkillsQuery,
  useCheckSkillUpdatesQuery,
  useCreateSkillMutation,
  useDiscoverAtomKindsMutation,
  useFetchSkillDetailQuery,
  useGetSkillContentQuery,
  useInstallAtomPackMutation,
  useInstallMcpAtomMutation,
  useInstallMcpBinaryMutation,
  useInstallSkillMutation,
  useLazyBrowseSkillsQuery,
  useLazyCheckAtomPackUpdateQuery,
  useLazyCheckSkillUpdatesQuery,
  useLazyFetchSkillDetailQuery,
  useLazyGetSkillContentQuery,
  useLazySearchSkillsQuery,
  useListAtomKindsQuery,
  useListAtomPacksQuery,
  useListInstalledMcpQuery,
  useListInstalledSkillsQuery,
  useListWorkplaceExperiencesQuery,
  useRemoveAtomPackMutation,
  useRemoveMcpAtomMutation,
  useRemoveSkillMutation,
  useSearchSkillsQuery,
  useSetAtomPackEnabledMutation,
  useSetAtomPinMutation,
  useSetMcpAtomEnabledMutation,
  useUpdateAtomPackMutation,
  useUpdateSkillContentMutation,
  useUpdateSkillMutation,
  useUploadSkillMutation
} from './endpoints/atoms/index.ts';
import {
  useDownloadAttachmentMutation,
  useGetAttachmentQuery,
  useLazyGetAttachmentQuery
} from './endpoints/attachments/index.ts';
import { useSendChannelMessageMutation } from './endpoints/channels/index.ts';
import { commandsApi, useLazyListCommandsQuery, useListCommandsQuery } from './endpoints/commands/index.ts';
import { useOpenDraftAttachmentMutation } from './endpoints/draft-attachments/index.ts';
import { graphApi, useGetGraphQuery } from './endpoints/graph/index.ts';
import {
  inboxApi,
  useGetInboxSummaryQuery,
  useListInboxQuery,
  useListMentionInboxQuery,
  useMarkAllInboxReadMutation,
  useMarkInboxReadMutation,
  useMarkInboxUnreadMutation
} from './endpoints/inbox/index.ts';
import { indexerApi, useGetIndexerStatusQuery } from './endpoints/indexer/get-indexer-status.ts';
import { useInitStatusQuery, useSetInitHomeMutation } from './endpoints/init/index.ts';
import { lawsApi, useGetLawsQuery } from './endpoints/laws/index.ts';
import { licensesApi, useListLicensesQuery } from './endpoints/licenses/index.ts';
import { mem0DataApi, useGetMem0DataQuery } from './endpoints/mem0-data/index.ts';
import {
  factSelectors,
  memoryApi,
  useAddMemoryFactMutation,
  useEditMemoryFactMutation,
  useForgetMemoryFactMutation,
  useGetMemoryCoreQuery,
  useGetMemoryStatusQuery,
  useListMemoryFactsQuery,
  usePrepareMemoryBackendMutation,
  usePutMemoryCoreMutation,
  useSetMem0ModelsMutation,
  useSetMemoryBackendMutation
} from './endpoints/memory/index.ts';
import {
  meshSessionAdapter,
  meshSessionSelectors,
  useApproveMeshSessionMutation,
  useGetMeshAgentAuthQuery,
  useGetMeshAgentConnectionQuery,
  useGetMeshAgentUsageQuery,
  useGetMeshSessionQuery,
  useGetMeshSessionUsageQuery,
  useGetMeshUsageOverviewQuery,
  useGetNativeAgentDeliveryQuery,
  useHeartbeatMeshAgentAuthMutation,
  useInputMeshAgentAuthMutation,
  useInputMeshSessionMutation,
  useLazyGetMeshAgentAuthStatusQuery,
  useLazyGetMeshAgentConnectionQuery,
  useLazyGetMeshAgentConvenienceEventsQuery,
  useLazyGetMeshAgentRawEventsQuery,
  useLazyGetMeshAgentUsageQuery,
  useListLiveMeshSessionsQuery,
  useListMeshSessionSummariesQuery,
  useListMeshSessionsQuery,
  useResizeMeshAgentAuthMutation,
  useResizeMeshSessionMutation,
  useStartMeshAgentAuthMutation,
  useStartMeshAgentMutation,
  useStopMeshAgentAuthMutation,
  useStopMeshSessionMutation,
  useStreamMeshAgentConvenienceQuery,
  useStreamMeshAgentRawQuery,
  useStreamMeshAgentStateQuery
} from './endpoints/mesh-agent/index.ts';
import {
  projectSessionAdapter,
  projectSessionSelectors,
  updateWorkplaceProjectApi,
  useCreateProjectSessionMutation,
  useCreateWorkplaceProjectMutation,
  useDeleteWorkplaceProjectMutation,
  useGetWorkplaceProjectQuery,
  useListProjectSessionsQuery,
  useListWorkplaceProjectsQuery,
  useReorderWorkplaceProjectMutation,
  useSendProjectMessageMutation,
  useUpdateWorkplaceProjectMutation,
  workplaceProjectAdapter,
  workplaceProjectSelectors
} from './endpoints/projects/index.ts';
import {
  projectRosterAdapter,
  projectRosterSelectors,
  sessionAdapter,
  sessionMemberAdapter,
  sessionMemberSelectors,
  sessionSelectors,
  useAbortSessionMutation,
  useAddSessionPlanTodoMutation,
  useBranchSessionMutation,
  useConsumeSessionAttentionMutation,
  useCreateSessionMutation,
  useDeleteSessionMutation,
  useDeleteSessionPlanTodoMutation,
  useForwardToAcpMutation,
  useGenerateMutation,
  useInviteSessionMemberMutation,
  useLazyGetUiItemsWindowQuery,
  useLazyResolveUiMessagesQuery,
  useListSessionAttentionQuery,
  useListSessionMembersQuery,
  useListSessionPlanQuery,
  useListSessionProjectRosterQuery,
  useListSessionsQuery,
  useRemoveSessionMemberMutation,
  useResetSessionMutation,
  useRestoreSessionMutation,
  useSearchSessionsQuery,
  useSendMessageMutation,
  useSpawnSessionMemberMutation,
  useStreamControlQuery,
  useStreamMessageGenerationQuery,
  useStreamUiItemsQuery,
  useUndoDeleteSessionMutation,
  useUpdateSessionMutation,
  useUpdateSessionPlanTodoMutation,
  useWorkspaceActionMutation,
  useWorkspaceGitQuery,
  useWorkspaceMetaQuery
} from './endpoints/sessions/index.ts';
import {
  acpAgentAdapter,
  acpAgentSelectors,
  useDeleteAcpAgentMutation,
  useListAcpAgentPresetsQuery,
  useListAcpAgentsQuery,
  useUpsertAcpAgentMutation
} from './endpoints/settings/acp-agents/index.ts';
import { useGetAppearanceQuery, useSetAppearanceMutation } from './endpoints/settings/appearance/index.ts';
import { useGetBrowserPresetQuery, useSetBrowserPresetMutation } from './endpoints/settings/browser-preset/index.ts';
import {
  channelAdapter,
  channelSelectors,
  channelsApi,
  useChannelStatusQuery,
  useDeleteChannelMutation,
  useListChannelsQuery,
  usePairChannelMutation,
  useSetChannelCredentialMutation,
  useUpsertChannelMutation
} from './endpoints/settings/channels/index.ts';
import { useGetComputerPresetQuery, useSetComputerPresetMutation } from './endpoints/settings/computer-preset/index.ts';
import {
  useCreateAgentCredentialMutation,
  useDeleteAgentCredentialMutation,
  useGetAgentCredentialCapabilityQuery,
  useListAgentCredentialsQuery,
  useUpdateAgentCredentialMutation
} from './endpoints/settings/credentials/index.ts';
import {
  useClearLogsMutation,
  useGetDeveloperQuery,
  useGetLiveEventReplayFramesQuery,
  useLazyGetLiveEventReplayFramesQuery,
  useListLiveEventReplayCapturesQuery,
  usePreviewLogCleanupMutation,
  useSetDeveloperMutation
} from './endpoints/settings/developer/index.ts';
import { useGetHooksQuery, useSetHooksMutation } from './endpoints/settings/hooks/index.ts';
import {
  useGetImportInventoryQuery,
  useOpenImportInventoryLocationMutation
} from './endpoints/settings/import-inventory/index.ts';
import {
  useApplySettingsImportMutation,
  usePreviewSettingsImportMutation
} from './endpoints/settings/import-settings/index.ts';
import {
  localeAdapter,
  localeApi,
  localeSelectors,
  useGetCatalogQuery,
  useGetLocaleQuery,
  useListLocalesQuery,
  useSetLocaleMutation
} from './endpoints/settings/locale/index.ts';
import {
  mcpServerAdapter,
  mcpServerSelectors,
  useAuthorizeMcpServerMutation,
  useCancelMcpTaskMutation,
  useDeleteMcpServerMutation,
  useLazyListMcpServerStatusQuery,
  useLazySearchMcpRegistryQuery,
  useListMcpCatalogQuery,
  useListMcpServerStatusQuery,
  useListMcpServersQuery,
  useReconnectMcpServerMutation,
  useSearchMcpRegistryQuery,
  useUpsertMcpServerMutation
} from './endpoints/settings/mcp-servers/index.ts';
import {
  meshAgentAdapter,
  meshAgentSelectors,
  useDeleteMeshAgentMutation,
  useListMeshAgentPresetsQuery,
  useListMeshAgentsQuery,
  useRefreshMeshAgentCatalogMutation,
  useUpsertMeshAgentMutation
} from './endpoints/settings/mesh-agents/index.ts';
import {
  credentialAdapter,
  credentialSelectors,
  modelAdapter,
  modelApi,
  modelSelectors,
  profileAdapter,
  profileSelectors,
  providerAdapter,
  providerSelectors,
  useAddCredentialMutation,
  useDeleteCredentialMutation,
  useDeleteProfileMutation,
  useDeleteProviderMutation,
  useGetDefaultQuery,
  useGetRolesQuery,
  useLazyListModelsQuery,
  useListCredentialsQuery,
  useListModelsQuery,
  useListProfilesQuery,
  useListProvidersQuery,
  useProviderCatalogQuery,
  useReindexEmbeddingsMutation,
  useRenameProfileMutation,
  useSetDefaultMutation,
  useSetProfileMutation,
  useSetProviderMutation,
  useSetRolesMutation,
  useTestConnectionMutation,
  useTestCredentialMutation,
  useTranscribeAudioMutation
} from './endpoints/settings/model/index.ts';
import {
  useGetNetworkQuery,
  useProbeNetworkMutation,
  useSetNetworkMutation
} from './endpoints/settings/network/index.ts';
import { useGetObscuraQuery, useSetObscuraMutation } from './endpoints/settings/obscura/index.ts';
import { useGetOpenaiCompatQuery, useSetOpenaiCompatMutation } from './endpoints/settings/openai-compat/index.ts';
import {
  peerAdapter,
  peerSelectors,
  useDeletePeerMutation,
  useGetPeerQuery,
  useListPeersQuery,
  useSetPeerCredentialMutation,
  useSetPeerEnabledMutation,
  useTestPeerConnectionMutation,
  useUpsertPeerMutation
} from './endpoints/settings/peers/index.ts';
import { useGetProfileSettingsQuery, useSetProfileSettingsMutation } from './endpoints/settings/profile/index.ts';
import {
  useActivateSandboxMutation,
  useGetSandboxQuery,
  useSetSandboxMutation
} from './endpoints/settings/sandbox/index.ts';
import { useGetSkillsSettingsQuery, useSetSkillsSettingsMutation } from './endpoints/settings/skills/index.ts';
import {
  useGetStartupQuery,
  useOpenStartupSettingsMutation,
  useSetStartupMutation
} from './endpoints/settings/startup/index.ts';
import {
  useGetToolBackendsQuery,
  useInitDockerBackendMutation,
  useSetToolBackendsMutation
} from './endpoints/settings/tool-backends/index.ts';
import { skillsApi, useListSkillsQuery } from './endpoints/skills/index.ts';
import { useGetHealthQuery } from './endpoints/system/get-health.ts';
import { useGetSystemUpgradeQuery } from './endpoints/system/get-system-upgrade.ts';
import { usePickDirectoryMutation } from './endpoints/system/pick-directory.ts';
import { useStartSystemUpgradeMutation } from './endpoints/system/start-system-upgrade.ts';
import { useApproveToolMutation } from './endpoints/tools/approve-tool.ts';
import { useClarifyRespondMutation } from './endpoints/tools/clarify-respond.ts';
import { useGetStatsQuery } from './endpoints/usage/get-stats.ts';
import { useGetUsageQuery } from './endpoints/usage/get-usage.ts';
import { useResetUsageMutation } from './endpoints/usage/reset-usage.ts';

export const monadApi = modelApi;

export type { MeshAgentStateStreamState } from './endpoints/mesh-agent/stream-mesh-agent-state.ts';
export type {
  CanonicalMessageChange,
  MessageGenerationStreamState,
  StreamMessageGenerationArg
} from './endpoints/sessions/index.ts';

export {
  acpAgentAdapter,
  acpAgentSelectors,
  agentAdapter,
  agentSelectors,
  approvalRuleSelectors,
  approvalsApi,
  atomPackAdapter,
  atomPackSelectors,
  atomsApi,
  channelAdapter,
  channelSelectors,
  channelsApi,
  commandsApi,
  credentialAdapter,
  credentialSelectors,
  factSelectors,
  graphApi,
  inboxApi,
  indexerApi,
  lawsApi,
  licensesApi,
  localeAdapter,
  localeApi,
  localeSelectors,
  mcpServerAdapter,
  mcpServerSelectors,
  mem0DataApi,
  memoryApi,
  meshAgentAdapter,
  meshAgentSelectors,
  meshSessionAdapter,
  meshSessionSelectors,
  modelAdapter,
  modelSelectors,
  peerAdapter,
  peerSelectors,
  profileAdapter,
  profileSelectors,
  projectRosterAdapter,
  projectRosterSelectors,
  projectSessionAdapter,
  projectSessionSelectors,
  providerAdapter,
  providerSelectors,
  sessionAdapter,
  sessionMemberAdapter,
  sessionMemberSelectors,
  sessionSelectors,
  skillsApi,
  updateWorkplaceProjectApi,
  useAbortSessionMutation,
  useActivateSandboxMutation,
  useAddCredentialMutation,
  useAddMemoryFactMutation,
  useAddSessionPlanTodoMutation,
  useApplySettingsImportMutation,
  useApproveMeshSessionMutation,
  useApproveToolMutation,
  useAuthorizeMcpServerMutation,
  useBranchSessionMutation,
  useBrowseSkillsQuery,
  useCancelMcpTaskMutation,
  useChannelStatusQuery,
  useCheckSkillUpdatesQuery,
  useClarifyRespondMutation,
  useClearApprovalsMutation,
  useClearLogsMutation,
  useConsumeSessionAttentionMutation,
  useCreateAgentCredentialMutation,
  useCreateAgentMutation,
  useCreateProjectSessionMutation,
  useCreateSessionMutation,
  useCreateSkillMutation,
  useCreateWorkplaceProjectMutation,
  useDeleteAcpAgentMutation,
  useDeleteAgentCredentialMutation,
  useDeleteAgentMutation,
  useDeleteChannelMutation,
  useDeleteCredentialMutation,
  useDeleteMcpServerMutation,
  useDeleteMeshAgentMutation,
  useDeletePeerMutation,
  useDeleteProfileMutation,
  useDeleteProviderMutation,
  useDeleteSessionMutation,
  useDeleteSessionPlanTodoMutation,
  useDeleteWorkplaceProjectMutation,
  useDiscoverAtomKindsMutation,
  useDownloadAttachmentMutation,
  useEditMemoryFactMutation,
  useFetchSkillDetailQuery,
  useForgetMemoryFactMutation,
  useForwardToAcpMutation,
  useGenerateMutation,
  useGetA2aStatusQuery,
  useGetAgentCredentialCapabilityQuery,
  useGetAgentPromptQuery,
  useGetAgentQuery,
  useGetAppearanceQuery,
  useGetAttachmentQuery,
  useGetBrowserPresetQuery,
  useGetCatalogQuery,
  useGetComputerPresetQuery,
  useGetDefaultAgentQuery,
  useGetDefaultQuery,
  useGetDeveloperQuery,
  useGetGraphQuery,
  useGetHealthQuery,
  useGetHooksQuery,
  useGetImportInventoryQuery,
  useGetInboxSummaryQuery,
  useGetIndexerStatusQuery,
  useGetLawsQuery,
  useGetLiveEventReplayFramesQuery,
  useGetLocaleQuery,
  useGetMem0DataQuery,
  useGetMemoryCoreQuery,
  useGetMemoryStatusQuery,
  useGetMeshAgentAuthQuery,
  useGetMeshAgentConnectionQuery,
  useGetMeshAgentUsageQuery,
  useGetMeshSessionQuery,
  useGetMeshSessionUsageQuery,
  useGetMeshUsageOverviewQuery,
  useGetNativeAgentDeliveryQuery,
  useGetNetworkQuery,
  useGetObscuraQuery,
  useGetOpenaiCompatQuery,
  useGetPeerQuery,
  useGetProfileSettingsQuery,
  useGetRolesQuery,
  useGetSandboxQuery,
  useGetSkillContentQuery,
  useGetSkillsSettingsQuery,
  useGetStartupQuery,
  useGetStatsQuery,
  useGetSystemUpgradeQuery,
  useGetToolBackendsQuery,
  useGetUsageQuery,
  useGetWorkplaceProjectQuery,
  useHeartbeatMeshAgentAuthMutation,
  useInitDockerBackendMutation,
  useInitStatusQuery,
  useInputMeshAgentAuthMutation,
  useInputMeshSessionMutation,
  useInstallAgentMcpMutation,
  useInstallAtomPackMutation,
  useInstallMcpAtomMutation,
  useInstallMcpBinaryMutation,
  useInstallSkillMutation,
  useInviteSessionMemberMutation,
  useLazyBrowseSkillsQuery,
  useLazyCheckAtomPackUpdateQuery,
  useLazyCheckSkillUpdatesQuery,
  useLazyFetchSkillDetailQuery,
  useLazyGetAttachmentQuery,
  useLazyGetLiveEventReplayFramesQuery,
  useLazyGetMeshAgentAuthStatusQuery,
  useLazyGetMeshAgentConnectionQuery,
  useLazyGetMeshAgentConvenienceEventsQuery,
  useLazyGetMeshAgentRawEventsQuery,
  useLazyGetMeshAgentUsageQuery,
  useLazyGetSkillContentQuery,
  useLazyGetUiItemsWindowQuery,
  useLazyListCommandsQuery,
  useLazyListMcpServerStatusQuery,
  useLazyListModelsQuery,
  useLazyResolveUiMessagesQuery,
  useLazySearchMcpRegistryQuery,
  useLazySearchSkillsQuery,
  useListAcpAgentPresetsQuery,
  useListAcpAgentsQuery,
  useListAgentCredentialsQuery,
  useListAgentsQuery,
  useListApprovalsQuery,
  useListAtomKindsQuery,
  useListAtomPacksQuery,
  useListChannelsQuery,
  useListCommandsQuery,
  useListCredentialsQuery,
  useListInboxQuery,
  useListInstalledMcpQuery,
  useListInstalledSkillsQuery,
  useListLicensesQuery,
  useListLiveEventReplayCapturesQuery,
  useListLiveMeshSessionsQuery,
  useListLocalesQuery,
  useListMcpCatalogQuery,
  useListMcpServerStatusQuery,
  useListMcpServersQuery,
  useListMemoryFactsQuery,
  useListMentionInboxQuery,
  useListMeshAgentPresetsQuery,
  useListMeshAgentsQuery,
  useListMeshSessionSummariesQuery,
  useListMeshSessionsQuery,
  useListModelsQuery,
  useListPeersQuery,
  useListProfilesQuery,
  useListProjectSessionsQuery,
  useListProvidersQuery,
  useListSessionAttentionQuery,
  useListSessionMembersQuery,
  useListSessionPlanQuery,
  useListSessionProjectRosterQuery,
  useListSessionsQuery,
  useListSkillsQuery,
  useListWorkplaceExperiencesQuery,
  useListWorkplaceProjectsQuery,
  useMarkAllInboxReadMutation,
  useMarkInboxReadMutation,
  useMarkInboxUnreadMutation,
  useOpenDraftAttachmentMutation,
  useOpenImportInventoryLocationMutation,
  useOpenStartupSettingsMutation,
  usePairChannelMutation,
  usePickDirectoryMutation,
  usePrepareMemoryBackendMutation,
  usePreviewLogCleanupMutation,
  usePreviewSettingsImportMutation,
  useProbeNetworkMutation,
  useProviderCatalogQuery,
  usePutMemoryCoreMutation,
  useReconnectMcpServerMutation,
  useRefreshMeshAgentCatalogMutation,
  useReindexEmbeddingsMutation,
  useRemoveAtomPackMutation,
  useRemoveMcpAtomMutation,
  useRemoveSessionMemberMutation,
  useRemoveSkillMutation,
  useRenameProfileMutation,
  useReorderWorkplaceProjectMutation,
  useResetSessionMutation,
  useResetUsageMutation,
  useResizeMeshAgentAuthMutation,
  useResizeMeshSessionMutation,
  useRestoreSessionMutation,
  useRevokeApprovalMutation,
  useSearchMcpRegistryQuery,
  useSearchSessionsQuery,
  useSearchSkillsQuery,
  useSendChannelMessageMutation,
  useSendMessageMutation,
  useSendProjectMessageMutation,
  useSetAgentPromptMutation,
  useSetAppearanceMutation,
  useSetAtomPackEnabledMutation,
  useSetAtomPinMutation,
  useSetBrowserPresetMutation,
  useSetChannelCredentialMutation,
  useSetComputerPresetMutation,
  useSetDefaultAgentMutation,
  useSetDefaultMutation,
  useSetDeveloperMutation,
  useSetHooksMutation,
  useSetInitHomeMutation,
  useSetLocaleMutation,
  useSetMcpAtomEnabledMutation,
  useSetMem0ModelsMutation,
  useSetMemoryBackendMutation,
  useSetNetworkMutation,
  useSetObscuraMutation,
  useSetOpenaiCompatMutation,
  useSetPeerCredentialMutation,
  useSetPeerEnabledMutation,
  useSetProfileMutation,
  useSetProfileSettingsMutation,
  useSetProviderMutation,
  useSetRolesMutation,
  useSetSandboxMutation,
  useSetSkillsSettingsMutation,
  useSetStartupMutation,
  useSetToolBackendsMutation,
  useSpawnSessionMemberMutation,
  useStartMeshAgentAuthMutation,
  useStartMeshAgentMutation,
  useStartSystemUpgradeMutation,
  useStopMeshAgentAuthMutation,
  useStopMeshSessionMutation,
  useStreamControlQuery,
  useStreamMeshAgentConvenienceQuery,
  useStreamMeshAgentRawQuery,
  useStreamMeshAgentStateQuery,
  useStreamMessageGenerationQuery,
  useStreamUiItemsQuery,
  useTestConnectionMutation,
  useTestCredentialMutation,
  useTestPeerConnectionMutation,
  useTranscribeAudioMutation,
  useUndoDeleteSessionMutation,
  useUpdateAgentCredentialMutation,
  useUpdateAgentMutation,
  useUpdateAtomPackMutation,
  useUpdateSessionMutation,
  useUpdateSessionPlanTodoMutation,
  useUpdateSkillContentMutation,
  useUpdateSkillMutation,
  useUpdateWorkplaceProjectMutation,
  useUploadSkillMutation,
  useUpsertAcpAgentMutation,
  useUpsertChannelMutation,
  useUpsertMcpServerMutation,
  useUpsertMeshAgentMutation,
  useUpsertPeerMutation,
  useWorkspaceActionMutation,
  useWorkspaceGitQuery,
  useWorkspaceMetaQuery,
  workplaceProjectAdapter,
  workplaceProjectSelectors
};
