export const SHELL_INSTALLER_AUTO_START = [
  'monad_warning() {',
  '    [ "$PRINT_QUIET" = "0" ] || return 0',
  `    if monad_is_interactive && [ -z "\${NO_COLOR:-}" ]; then`,
  '        printf \'\\033[1;33m  !\\033[0m \\033[2m%s\\033[0m\\n\' "$1" >&2',
  '    else',
  '        printf \'  ! %s\\n\' "$1" >&2',
  '    fi',
  '}',
  '',
  'monad_start_after_install() {',
  '    _monad_install_dir="$1"',
  '    _monad_binary="$_monad_install_dir/monad"',
  '    monad_is_interactive || return 0',
  '    monad_step "Starting Monad"',
  '    if "$_monad_binary" up; then',
  '        monad_done "Monad started"',
  '        return 0',
  '    else',
  '        _monad_start_status=$?',
  '    fi',
  '    monad_warning "Monad installed, but automatic startup failed (exit $_monad_start_status). Run $_monad_binary up manually."',
  '    return 0',
  '}'
].join('\n');

export const POWERSHELL_INSTALLER_AUTO_START = [
  'function Write-MonadWarning($message) {',
  "  if ($env:MONAD_PRINT_QUIET -eq '1') { return }",
  '  Write-Host "  !" -NoNewline -ForegroundColor Yellow',
  '  Write-Host " $message" -ForegroundColor DarkGray',
  '}',
  '',
  'function Start-MonadAfterInstall($installDir) {',
  '  if (-not (Test-MonadInteractive)) { return }',
  "  $binary = Join-Path $installDir 'monad.exe'",
  '  Write-MonadStep "Starting Monad"',
  '  try {',
  '    & $binary up',
  '    if ($LASTEXITCODE -ne 0) { throw "exit code $LASTEXITCODE" }',
  '    Write-MonadDone "Monad started"',
  '  } catch {',
  '    $message = Get-ExceptionMessage $_.Exception',
  '    Write-MonadWarning "Monad installed, but automatic startup failed ($message). Run $binary up manually."',
  '  }',
  '}'
].join('\n');
