export const SHELL_INSTALLER_AUTO_START = [
  'monad_warning() {',
  '    [ "$PRINT_QUIET" = "0" ] || return 0',
  `    if monad_is_interactive && [ -z "\${NO_COLOR:-}" ]; then`,
  '        printf \'\\033[1;33m  !\\033[0m \\033[2m%s\\033[0m\\n\' "$1" >&2',
  '    else',
  '        printf \'  ! %s\\n\' "$1" >&2',
  '    fi',
  '}',
  '',
  'monad_start_after_install() {',
  '    _monad_install_dir="$1"',
  '    _monad_binary="$_monad_install_dir/monad"',
  '    monad_is_interactive || return 0',
  '    _monad_launch_command="up"',
  '    _monad_launch_label="Starting Monad"',
  '    _monad_daemon_status=$("$_monad_binary" status --json 2>/dev/null) && _monad_daemon_reachable=1 || _monad_daemon_reachable=0',
  `    _monad_daemon_version=$(printf '%s' "$_monad_daemon_status" | sed -n 's/.*"version":"\\([^"]*\\)".*/\\1/p' | head -n 1)`,
  '    if [ "$_monad_daemon_reachable" = "1" ] && [ "$_monad_daemon_version" != "$APP_VERSION" ]; then',
  '        _monad_launch_command="restart"',
  '        _monad_launch_label="Restarting Monad"',
  '    fi',
  '    monad_step "$_monad_launch_label"',
  '    if "$_monad_binary" "$_monad_launch_command"; then',
  '        if [ "$_monad_launch_command" = "restart" ]; then',
  '            "$_monad_binary" up',
  '            _monad_start_status=$?',
  '            if [ "$_monad_start_status" -ne 0 ]; then',
  '                monad_warning "Monad installed and restarted, but opening it failed (exit $_monad_start_status). Run $_monad_binary up manually."',
  '                return 0',
  '            fi',
  '        fi',
  '        monad_done "Monad started"',
  '        return 0',
  '    else',
  '        _monad_start_status=$?',
  '    fi',
  '    monad_warning "Monad installed, but automatic startup failed (exit $_monad_start_status). Run $_monad_binary up manually."',
  '    return 0',
  '}'
].join('\n');

export const POWERSHELL_INSTALLER_AUTO_START = [
  'function Write-MonadWarning($message) {',
  "  if ($env:MONAD_PRINT_QUIET -eq '1') { return }",
  '  Write-Host "  !" -NoNewline -ForegroundColor Yellow',
  '  Write-Host " $message" -ForegroundColor DarkGray',
  '}',
  '',
  '$script:MonadRestartAfterInstall = $false',
  '',
  'function Stop-MonadBeforeInstall($installDir) {',
  '  if (-not (Test-MonadInteractive)) { return }',
  "  $binary = Join-Path $installDir 'monad.exe'",
  '  if (-not (Test-Path -LiteralPath $binary)) { return }',
  '  & $binary status --json 2>$null | Out-Null',
  '  if ($LASTEXITCODE -ne 0) { return }',
  '  Write-MonadStep "Stopping Monad"',
  '  & $binary stop',
  '  if ($LASTEXITCODE -ne 0) { throw "failed to stop the running Monad daemon (exit code $LASTEXITCODE)" }',
  '  $script:MonadRestartAfterInstall = $true',
  '}',
  '',
  'function Start-MonadAfterInstall($installDir) {',
  '  if (-not (Test-MonadInteractive)) { return }',
  "  $binary = Join-Path $installDir 'monad.exe'",
  "  $launchLabel = if ($script:MonadRestartAfterInstall) { 'Restarting Monad' } else { 'Starting Monad' }",
  '  try {',
  '    Write-MonadStep $launchLabel',
  '    & $binary up',
  '    if ($LASTEXITCODE -ne 0) { throw "exit code $LASTEXITCODE" }',
  '    Write-MonadDone "Monad started"',
  '  } catch {',
  '    $message = Get-ExceptionMessage $_.Exception',
  '    Write-MonadWarning "Monad installed, but automatic startup failed ($message). Run $binary up manually."',
  '  }',
  '}'
].join('\n');
