// Generated by apps/monad/scripts/generate-migration-assets.ts. Do not edit by hand.

import type { MigrationMeta } from 'drizzle-orm/migrator';

// biome-ignore format: generated migration data mirrors the source SQL exactly.
export const MIGRATIONS: MigrationMeta[] = [
  {
    "sql": [
      "CREATE TABLE `acp_delegates` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`agent_name` text NOT NULL,\n\t`acp_session_id` text NOT NULL,\n\t`pid` integer NOT NULL,\n\t`spawned_at` text NOT NULL,\n\t`last_used_at` text NOT NULL,\n\t`evicted_at` text,\n\t`evict_reason` text,\n\t`reuse_count` integer DEFAULT 0 NOT NULL,\n\t`prompt_count` integer DEFAULT 0 NOT NULL\n);\n",
      "\nCREATE INDEX `idx_acp_delegates_session` ON `acp_delegates` (`session_id`);",
      "\nCREATE INDEX `idx_acp_delegates_live` ON `acp_delegates` (`evicted_at`) WHERE evicted_at IS NULL;",
      "\nCREATE TABLE `channel_conversation_sessions` (\n\t`channel_id` text NOT NULL,\n\t`conversation_key` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`label` text,\n\t`created_at` text NOT NULL,\n\tPRIMARY KEY(`channel_id`, `conversation_key`, `session_id`)\n);\n",
      "\nCREATE INDEX `idx_channel_conv_sessions_session` ON `channel_conversation_sessions` (`session_id`);",
      "\nCREATE TABLE `channel_conversations` (\n\t`channel_id` text NOT NULL,\n\t`conversation_key` text NOT NULL,\n\t`active_session_id` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`last_seen_at` text NOT NULL,\n\tPRIMARY KEY(`channel_id`, `conversation_key`)\n);\n",
      "\nCREATE TABLE `events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`transcript_target_id` text NOT NULL,\n\t`type` text NOT NULL,\n\t`actor_agent_id` text,\n\t`task_id` text,\n\t`payload` text NOT NULL,\n\t`at` text NOT NULL\n);\n",
      "\nCREATE INDEX `idx_events_transcript_target` ON `events` (`transcript_target_id`,`id`);",
      "\nCREATE TABLE `experience_state` (\n\t`atom_pack_id` text NOT NULL,\n\t`project_id` text NOT NULL,\n\t`record_key` text NOT NULL,\n\t`value` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\tPRIMARY KEY(`atom_pack_id`, `project_id`, `record_key`)\n);\n",
      "\nCREATE INDEX `idx_experience_state_project` ON `experience_state` (`atom_pack_id`,`project_id`,`record_key`);",
      "\nCREATE TABLE `experience_state_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`atom_pack_id` text NOT NULL,\n\t`project_id` text NOT NULL,\n\t`record_key` text NOT NULL,\n\t`version` integer NOT NULL,\n\t`payload` text NOT NULL,\n\t`created_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `idx_experience_state_events_record` ON `experience_state_events` (`atom_pack_id`,`project_id`,`record_key`,`version`);",
      "\nCREATE TABLE `experience_worker_wakeups` (\n\t`atom_pack_id` text NOT NULL,\n\t`experience_id` text NOT NULL,\n\t`project_id` text NOT NULL,\n\t`wake_key` text NOT NULL,\n\t`run_at` text NOT NULL,\n\t`attempt` integer DEFAULT 0 NOT NULL,\n\t`updated_at` text NOT NULL,\n\tPRIMARY KEY(`atom_pack_id`, `experience_id`, `project_id`, `wake_key`)\n);\n",
      "\nCREATE INDEX `idx_experience_worker_wakeups_due` ON `experience_worker_wakeups` (`run_at`);",
      "\nCREATE TABLE `file_observations` (\n\t`session_id` text NOT NULL,\n\t`path` text NOT NULL,\n\t`hash` text NOT NULL,\n\t`coverage` text NOT NULL,\n\t`observed_at` text NOT NULL,\n\t`tool_call_id` text,\n\tPRIMARY KEY(`session_id`, `path`)\n);\n",
      "\nCREATE INDEX `idx_file_observations_session` ON `file_observations` (`session_id`);",
      "\nCREATE TABLE `memory` (\n\t`session_id` text NOT NULL,\n\t`key` text NOT NULL,\n\t`value` text NOT NULL,\n\tPRIMARY KEY(`session_id`, `key`)\n);\n",
      "\nCREATE TABLE `mesh_agent_inbox_items` (\n\t`mesh_session_id` text NOT NULL,\n\t`message_seq` integer NOT NULL,\n\t`delivery_id` text,\n\t`project_id` text,\n\t`member_instance_id` text,\n\t`trigger_message_id` text,\n\t`provider_session_ref` text,\n\t`provider_turn_id` text,\n\t`error_summary` text,\n\t`state` text DEFAULT 'queued' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`delivered_at` text,\n\t`visible_at` text,\n\t`consumed_at` text,\n\t`updated_at` text,\n\tPRIMARY KEY(`mesh_session_id`, `message_seq`)\n);\n",
      "\nCREATE INDEX `idx_mesh_agent_inbox_items_pending` ON `mesh_agent_inbox_items` (`mesh_session_id`,`state`,`message_seq`);",
      "\nCREATE UNIQUE INDEX `idx_mesh_agent_inbox_delivery_id` ON `mesh_agent_inbox_items` (`delivery_id`) WHERE delivery_id IS NOT NULL;",
      "\nCREATE INDEX `idx_mesh_agent_inbox_project_trigger` ON `mesh_agent_inbox_items` (`project_id`,`trigger_message_id`);",
      "\nCREATE INDEX `idx_mesh_agent_inbox_member_state` ON `mesh_agent_inbox_items` (`project_id`,`member_instance_id`,`state`);",
      "\nCREATE TABLE `mesh_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`transcript_target_id` text NOT NULL,\n\t`agent_name` text NOT NULL,\n\t`provider` text NOT NULL,\n\t`working_path` text NOT NULL,\n\t`runtime_role` text DEFAULT 'interactive' NOT NULL,\n\t`agent_runtime_id` text,\n\t`agent_runtime_token_hash` text,\n\t`last_delivered_seq` integer DEFAULT 0 NOT NULL,\n\t`last_visible_seq` integer DEFAULT 0 NOT NULL,\n\t`state` text NOT NULL,\n\t`pid` integer,\n\t`provider_session_ref` text,\n\t`exit_code` integer,\n\t`started_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`exited_at` text\n);\n",
      "\nCREATE INDEX `idx_mesh_sessions_transcript_target` ON `mesh_sessions` (`transcript_target_id`);",
      "\nCREATE INDEX `idx_mesh_sessions_live` ON `mesh_sessions` (`state`) WHERE state IN ('starting', 'running');",
      "\nCREATE UNIQUE INDEX `idx_mesh_sessions_provider_ref` ON `mesh_sessions` (`transcript_target_id`,`provider`,`provider_session_ref`) WHERE provider_session_ref IS NOT NULL;",
      "\nCREATE TABLE `message_attachments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`path` text NOT NULL,\n\t`name` text NOT NULL,\n\t`mime` text NOT NULL,\n\t`bytes` integer NOT NULL,\n\t`preview` text NOT NULL,\n\t`created_by` text,\n\t`created_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `idx_message_attachments_project` ON `message_attachments` (`project_id`);",
      "\nCREATE TABLE `message_embeddings` (\n\t`message_id` text PRIMARY KEY NOT NULL,\n\t`dim` integer NOT NULL,\n\t`vec` blob NOT NULL,\n\t`model` text\n);\n",
      "\nCREATE TABLE `message_mutations` (\n\t`transcript_target_id` text NOT NULL,\n\t`idempotency_key` text NOT NULL,\n\t`command_fingerprint` text NOT NULL,\n\t`message_id` text NOT NULL,\n\t`message_revision` integer NOT NULL,\n\t`result_message` text NOT NULL,\n\tPRIMARY KEY(`transcript_target_id`, `idempotency_key`)\n);\n",
      "\nCREATE TABLE `messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`transcript_target_id` text NOT NULL,\n\t`role` text NOT NULL,\n\t`text` text NOT NULL,\n\t`type` text DEFAULT 'text' NOT NULL,\n\t`data` text,\n\t`stream_status` text DEFAULT 'settled' NOT NULL,\n\t`active` integer DEFAULT 1 NOT NULL,\n\t`include_in_context` integer,\n\t`idempotency_key` text,\n\t`command_fingerprint` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text\n);\n",
      "\nCREATE INDEX `idx_messages_transcript_target` ON `messages` (`transcript_target_id`);",
      "\nCREATE INDEX `idx_messages_active` ON `messages` (`transcript_target_id`,`active`);",
      "\nCREATE UNIQUE INDEX `idx_messages_target_idempotency` ON `messages` (`transcript_target_id`,`idempotency_key`);",
      "\nCREATE TABLE `native_agent_direct_messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`mesh_session_id` text NOT NULL,\n\t`from_agent` text,\n\t`peer` text NOT NULL,\n\t`text` text NOT NULL,\n\t`attachment_ids` text,\n\t`created_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `idx_native_agent_direct_messages_session_peer` ON `native_agent_direct_messages` (`mesh_session_id`,`peer`,`created_at`);",
      "\nCREATE INDEX `idx_native_agent_direct_messages_project_pair` ON `native_agent_direct_messages` (`project_id`,`from_agent`,`peer`,`created_at`);",
      "\nCREATE TABLE `session_members` (\n\t`session_id` text NOT NULL,\n\t`member_id` text NOT NULL,\n\t`template_id` text,\n\t`type` text NOT NULL,\n\t`mesh_session_id` text,\n\t`data` text DEFAULT '{}' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tPRIMARY KEY(`session_id`, `member_id`)\n);\n",
      "\nCREATE INDEX `idx_session_members_session` ON `session_members` (`session_id`);",
      "\nCREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text,\n\t`title` text NOT NULL,\n\t`state` text NOT NULL,\n\t`agent_ids` text DEFAULT '[]' NOT NULL,\n\t`archived` integer DEFAULT 0 NOT NULL,\n\t`restore_count` integer DEFAULT 0 NOT NULL,\n\t`model` text,\n\t`cwd` text,\n\t`origin` text,\n\t`input_tokens` integer DEFAULT 0 NOT NULL,\n\t`output_tokens` integer DEFAULT 0 NOT NULL,\n\t`total_tokens` integer DEFAULT 0 NOT NULL,\n\t`cache_read_tokens` integer DEFAULT 0 NOT NULL,\n\t`cache_write_tokens` integer DEFAULT 0 NOT NULL,\n\t`reasoning_tokens` integer DEFAULT 0 NOT NULL,\n\t`cost_usd` real DEFAULT 0 NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `idx_sessions_project` ON `sessions` (`project_id`);",
      "\nCREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`assignee_agent_id` text,\n\t`depends_on` text DEFAULT '[]' NOT NULL,\n\t`state` text NOT NULL,\n\t`version` integer DEFAULT 0 NOT NULL,\n\t`result` text,\n\t`error` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `idx_tasks_session` ON `tasks` (`session_id`);",
      "\nCREATE TABLE `tool_raw_outputs` (\n\t`transcript_target_id` text NOT NULL,\n\t`tool_call_id` text NOT NULL,\n\t`output` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tPRIMARY KEY(`transcript_target_id`, `tool_call_id`)\n);\n",
      "\nCREATE TABLE `transcript_message_revisions` (\n\t`transcript_target_id` text PRIMARY KEY NOT NULL,\n\t`revision` integer DEFAULT 0 NOT NULL\n);\n",
      "\nCREATE TABLE `usage_ledger` (\n\t`day` text NOT NULL,\n\t`provider` text NOT NULL,\n\t`model` text NOT NULL,\n\t`category` text DEFAULT 'chat' NOT NULL,\n\t`input_tokens` integer DEFAULT 0 NOT NULL,\n\t`output_tokens` integer DEFAULT 0 NOT NULL,\n\t`cache_read_tokens` integer DEFAULT 0 NOT NULL,\n\t`cache_write_tokens` integer DEFAULT 0 NOT NULL,\n\t`reasoning_tokens` integer DEFAULT 0 NOT NULL,\n\t`cost_usd` real DEFAULT 0 NOT NULL,\n\t`updated_at` text NOT NULL,\n\tPRIMARY KEY(`day`, `provider`, `model`, `category`)\n);\n",
      "\nCREATE TABLE `workplace_projects` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`state` text NOT NULL,\n\t`archived` integer DEFAULT 0 NOT NULL,\n\t`model` text,\n\t`cwd` text,\n\t`origin` text,\n\t`member_templates` text DEFAULT '[]' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `idx_workplace_projects_state` ON `workplace_projects` (`state`,`archived`);"
    ],
    "bps": true,
    "folderMillis": 1784472030662,
    "hash": "0d59650475487ede5d8baaff5b6502bcc3842d9017ac19241c3ebfc93037ea02"
  },
  {
    "sql": [
      "CREATE VIRTUAL TABLE IF NOT EXISTS `messages_fts`\nUSING fts5(`text`, content='messages', content_rowid='rowid');\n",
      "\nCREATE VIRTUAL TABLE IF NOT EXISTS `messages_fts_trigram`\nUSING fts5(`text`, content='messages', content_rowid='rowid', tokenize='trigram');\n",
      "\nCREATE TRIGGER IF NOT EXISTS `messages_ai` AFTER INSERT ON `messages` BEGIN\n  INSERT INTO messages_fts(rowid, text) VALUES (new.rowid, new.text);\n  INSERT INTO messages_fts_trigram(rowid, text) VALUES (new.rowid, new.text);\nEND;\n",
      "\nCREATE TRIGGER IF NOT EXISTS `messages_ad` AFTER DELETE ON `messages` BEGIN\n  INSERT INTO messages_fts(messages_fts, rowid, text) VALUES ('delete', old.rowid, old.text);\n  INSERT INTO messages_fts_trigram(messages_fts_trigram, rowid, text) VALUES ('delete', old.rowid, old.text);\nEND;\n",
      "\nCREATE TRIGGER IF NOT EXISTS `messages_au` AFTER UPDATE ON `messages` BEGIN\n  INSERT INTO messages_fts(messages_fts, rowid, text) VALUES ('delete', old.rowid, old.text);\n  INSERT INTO messages_fts_trigram(messages_fts_trigram, rowid, text) VALUES ('delete', old.rowid, old.text);\n  INSERT INTO messages_fts(rowid, text) VALUES (new.rowid, new.text);\n  INSERT INTO messages_fts_trigram(rowid, text) VALUES (new.rowid, new.text);\nEND;\n",
      "\nINSERT INTO messages_fts(messages_fts) VALUES ('rebuild');\n",
      "\nINSERT INTO messages_fts_trigram(messages_fts_trigram) VALUES ('rebuild');\n"
    ],
    "bps": true,
    "folderMillis": 1784472067634,
    "hash": "60e311db225abad53357805d7914bab5e209a2e560ee2484d1e8dd886c4151e5"
  },
  {
    "sql": [
      "CREATE TABLE `inbox_item_reads` (\n\t`item_key` text PRIMARY KEY NOT NULL,\n\t`read_at` text NOT NULL\n);\n"
    ],
    "bps": true,
    "folderMillis": 1784570505472,
    "hash": "d6d37237afb74b93a7e514af1814b2c6c82f0a67ec713a38d4420a896b0674da"
  },
  {
    "sql": [
      "-- Custom SQL migration file, put your code below! --\n-- `message_attachments.project_id` and `native_agent_direct_messages.project_id` have always held\n-- a session id (transcript_target_id / mesh session's session), never a `prj_*` Workplace Project\n-- id. The column name was wrong from day one, which made every delete path keyed on it silently\n-- match zero rows. Rename to the value the column actually holds.\nALTER TABLE `message_attachments` RENAME COLUMN `project_id` TO `session_id`;\n",
      "\nDROP INDEX `idx_message_attachments_project`;\n",
      "\nCREATE INDEX `idx_message_attachments_session` ON `message_attachments` (`session_id`);\n",
      "\nALTER TABLE `native_agent_direct_messages` RENAME COLUMN `project_id` TO `session_id`;\n",
      "\nDROP INDEX `idx_native_agent_direct_messages_project_pair`;\n",
      "\nCREATE INDEX `idx_native_agent_direct_messages_session_pair` ON `native_agent_direct_messages` (`session_id`,`from_agent`,`peer`,`created_at`);\n",
      "\n\n-- Repair pass — two independent leaks the rename above does not fix by itself:\n--\n-- (A) `deleteWorkplaceProject` never cascaded to the sessions it owns: it deleted rows matching\n--     `transcript_target_id = <prj_id>` / `project_id = <prj_id>`, which never matched anything\n--     scoped by session id, and it never touched the `sessions` table at all. A project delete\n--     left every contained session's messages, events, tool output, DMs, and attachments in\n--     place, with the session still pointing at a `project_id` that no longer resolves.\n--\n-- (B) `deleteSession` used the same mislabeled `project_id` column for direct messages and (once\n--     attachments existed) would have missed attachments too, leaving those two tables' rows\n--     behind for sessions that otherwise deleted cleanly.\n--\n-- Both leave orphaned data now that ownership is named correctly, so purge it in one pass: first\n-- everything owned by a \"zombie\" session (a session whose project was deleted out from under it),\n-- then the zombie sessions themselves, then anything in the two renamed tables that still points\n-- at a session id no longer present at all (case B).\n\nDELETE FROM `message_embeddings`\nWHERE `message_id` IN (\n  SELECT `id` FROM `messages` WHERE `transcript_target_id` IN (\n    SELECT `id` FROM `sessions`\n    WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n  )\n);\n",
      "\nDELETE FROM `tasks`\nWHERE `session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `memory`\nWHERE `session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `file_observations`\nWHERE `session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `messages`\nWHERE `transcript_target_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `events`\nWHERE `transcript_target_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `tool_raw_outputs`\nWHERE `transcript_target_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `acp_delegates`\nWHERE `session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `channel_conversation_sessions`\nWHERE `session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `channel_conversations`\nWHERE `active_session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `mesh_agent_inbox_items`\nWHERE `mesh_session_id` IN (\n  SELECT `id` FROM `mesh_sessions` WHERE `transcript_target_id` IN (\n    SELECT `id` FROM `sessions`\n    WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n  )\n);\n",
      "\nDELETE FROM `mesh_sessions`\nWHERE `transcript_target_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `native_agent_direct_messages`\nWHERE `session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `message_attachments`\nWHERE `session_id` IN (\n  SELECT `id` FROM `sessions`\n  WHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`)\n);\n",
      "\nDELETE FROM `sessions`\nWHERE `project_id` IS NOT NULL AND `project_id` NOT IN (SELECT `id` FROM `workplace_projects`);\n",
      "\nDELETE FROM `experience_state` WHERE `project_id` NOT IN (SELECT `id` FROM `workplace_projects`);\n",
      "\nDELETE FROM `experience_state_events` WHERE `project_id` NOT IN (SELECT `id` FROM `workplace_projects`);\n",
      "\nDELETE FROM `experience_worker_wakeups` WHERE `project_id` NOT IN (SELECT `id` FROM `workplace_projects`);\n",
      "\n\n-- Case (B): rows in the two renamed tables left behind by an individually-deleted session (the\n-- session row itself is already gone, so these can't be reached by the project-zombie sweep above).\nDELETE FROM `native_agent_direct_messages`\nWHERE `session_id` NOT IN (SELECT `id` FROM `sessions`);\n",
      "\nDELETE FROM `message_attachments`\nWHERE `session_id` NOT IN (SELECT `id` FROM `sessions`);\n"
    ],
    "bps": true,
    "folderMillis": 1784575466826,
    "hash": "ab415f7c831c57ea3c966798a812617ee64d958399a56db13534c04f6449553e"
  }
];

export const LATEST_MIGRATION_TIMESTAMP = 1784575466826;
