#!/usr/bin/env bun
import { join, resolve } from 'node:path';

import { listAvatarStyleSlugs } from './avatar-style-slugs.ts';

// Enumerate the avatar styles shipped by the installed @dicebear/styles package (one
// `dist/<slug>.min.json` per style) and emit the slug union as a local generated artifact, so the
// wire enum in packages/protocol/src/avatar.ts is derived from the package rather than
// hand-maintained. Generated artifacts are refreshed by the project hook.
// apps/monad owns the @dicebear/styles dependency, so resolve from there (bun does not hoist).

const ROOT = resolve(import.meta.dir, '..');
const OUT = join(ROOT, 'packages/protocol/generated/avatar-styles.ts');

const slugs = await listAvatarStyleSlugs(ROOT);

const body = `// GENERATED CODE — DO NOT EDIT. Regenerated by the project hook.
// The full set of avatar styles shipped by @dicebear/styles, enumerated from the installed package
// so the wire enum in avatar.ts never has to be hand-maintained. avatar-styles.test.ts asserts this
// still matches the package, so a @dicebear/styles upgrade that adds/removes a style fails a test.

export const AVATAR_STYLE_SLUGS = [
${slugs.map((slug) => `  '${slug}'`).join(',\n')}
] as const;
`;

await Bun.write(OUT, body);
