// Generated by scripts/i18n.ts. Do not edit by hand.

import en_channel from './locales/en/channel.json';
import en_cli from './locales/en/cli.json';
import en_cmd from './locales/en/cmd.json';
import en_daemon from './locales/en/daemon.json';
import en_init from './locales/en/init.json';
import en_web from './locales/en/web.json';
import zh_channel from './locales/zh/channel.json';
import zh_cli from './locales/zh/cli.json';
import zh_cmd from './locales/zh/cmd.json';
import zh_daemon from './locales/zh/daemon.json';
import zh_init from './locales/zh/init.json';
import zh_web from './locales/zh/web.json';

function mergeCatalogs(catalogs: readonly Record<string, string>[]): Record<string, string> {
  return Object.assign({}, ...catalogs);
}

export const enMessages = mergeCatalogs([en_channel, en_cli, en_cmd, en_daemon, en_init, en_web]);
export const zhMessages = mergeCatalogs([zh_channel, zh_cli, zh_cmd, zh_daemon, zh_init, zh_web]);
